#!/usr/bin/env node
/* vim: set ft=javascript: */

var fs = require('fs'),
    prettyjson = require('prettyjson');
    pro = require("uglify-js").uglify,
    peg = require('pegjs');

var log = console.log.bind(console);

var grammar = fs.readFileSync('sil.peg', 'utf-8'),
    // demo = fs.readFileSync('v311.sil', 'utf-8');
    demo = fs.readFileSync('dummy.sil', 'utf-8');

console.log('Building the parser...');
parser = peg.buildParser(grammar);

console.log('Parsing demo...');
output = parser.parse(demo)
console.log('-------- PARSE TREE ------');
console.log(JSON.stringify(output, null, 4));
console.log('-------- JAVASCRIPT CODE ------');
var code = pro.gen_code(output, {beautify: true});
console.log(code);
