#!/usr/bin/env node
/* vim: set ft=javascript: */

(function (args) {
    "use strict";

    var fs = require('fs'),
        peg = require('pegjs'),
        uglify = require('uglify-js'),
        grammar = fs.readFileSync('sil.peg', 'utf-8'),
        sil = peg.buildParser(grammar),
        js = {
            generate : uglify.uglify.gen_code.bind(uglify.uglify),
            parse    : uglify.parser.parse.bind(uglify.parser)
        };

    args.forEach(function (infile) {
        var src = fs.readFileSync(infile, 'utf-8'),
            ast = sil.parse(src),
            code = js.generate(ast, {
                beautify     : true,
                indent_level : 2,
                space_colon  : true
            });
        code = tidy(code);
        console.log(code);
    });

    function tidy(code) {
        var depth = 0;

        code = code.replace(/\s+/g, ' ');
        code = code.replace(/[\[\]]./g, function (match) {
            depth = depth - match.charCodeAt(0) + 92;
            return depth === 1 ? match + '\n' : match;
        });

        code = code.split('\n').map(function (ln) {
            var i, tabstop;

            ln = ln.split(/\s*,\s*/g);

            if (ln.length > 2) {
                for (i = 1; i < 3; i++) {
                    tabstop = 13 - i - ln[i - 1].trim().length;
                    if (tabstop > 0) {
                        ln[i] = new Array(tabstop).join(' ') + ln[i];
                    }
                }
            }

            return ln.join(', ').trim();
        }).join('\n');

        return code;
    }

}(process.argv.slice(2)));
