var PEG = require( 'pegjs' ),
    fs = require( 'fs' ),
    escodegen = require( 'escodegen' ),
    grammar = fs.readFileSync( __dirname + '/sil.peg' ).toString( 'utf-8' ),
    snobol = fs.readFileSync( __dirname + '/../external/v311.sil' ).toString( 'utf-8' ),
    parser = PEG.generate( grammar ),
    ast = parser.parse( snobol ),
    prolog = (
	"// This file was automatically generated by src/translate.js.\n" +
	"var SNOBOL = require( './base' );\n"
    ),
    code = prolog + escodegen.generate( ast );

console.log( code );
