// Translates the SIL source code into JavaScript.
// The PEG grammar generates an ESTree-compatible AST.
// Currently, we use astring (https://github.com/davidbonnet/astring) to
// generate the JavaScript code from the AST, but escodegen works just as well.
var PEG = require( 'pegjs' ),
    fs = require( 'fs' ),
    astring = require( 'astring' ),
    grammar = fs.readFileSync( __dirname + '/sil.peg' ).toString( 'utf-8' ),
    snobol = fs.readFileSync( __dirname + '/../external/v311.sil' ).toString( 'utf-8' ),
    parser = PEG.generate( grammar ),
    ast = parser.parse( snobol ),
    prolog = (
	"// This file was automatically generated by src/translate.js.\n" +
	"var SNOBOL = require( './base' );\n"
    ),
    code = prolog + astring.generate( ast ).trim();

console.log( code );
