// Translates the SIL source code into JavaScript.
// The PEG grammar generates an ESTree-compatible AST.
// Currently, we use astring (https://github.com/davidbonnet/astring) to
// generate the JavaScript code from the AST, but escodegen works just as well.
import PEG from 'pegjs';
import fs from 'node:fs';
import astring from 'astring';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

var __dirname = dirname( fileURLToPath( import.meta.url ) );
var source = __dirname + '/../external/v311-snoflake.sil',
    grammar = fs.readFileSync( __dirname + '/sil.peg' ).toString( 'utf-8' ),
    snobol = fs.readFileSync( source ).toString( 'utf-8' ),
    parser = PEG.generate( grammar ),
    ast = parser.parse( snobol ),
    prolog = (
	"// This file was automatically generated by src/translate.js.\n" +
	"// Source: external/v311-snoflake.sil\n" +
	"import SNOBOL from './base.js';\n"
    ),
    code = prolog + astring.generate( ast ).trim();

console.log( code );
