// Translates the SIL source code into JavaScript.
// The PEG grammar generates an ESTree-compatible AST.
// Currently, we use astring (https://github.com/davidbonnet/astring) to
// generate the JavaScript code from the AST, but escodegen works just as well.
import peggy from 'peggy';
import fs from 'node:fs';
import { generate as astringGenerate } from 'astring';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const __dirname = dirname( fileURLToPath( import.meta.url ) );
const source = __dirname + '/../external/v311-snoflake.sil',
      grammar = fs.readFileSync( __dirname + '/sil.peg' ).toString( 'utf-8' ),
      snobol = fs.readFileSync( source ).toString( 'utf-8' ),
      parser = peggy.generate( grammar ),
      ast = parser.parse( snobol ),
      prolog = (
	"// This file was automatically generated by translator/translate.js.\n" +
	"// Source: external/v311-snoflake.sil\n" +
	"import SNOBOL from './base.js';\n"
      ),
      code = prolog + astringGenerate( ast ).trim();

console.log( code );
