// Translates the SIL source code into JavaScript.
// The PEG grammar generates an ESTree-compatible AST for the source-level SIL
// listing.  Translation evaluates that listing once, assembles it, and emits a
// runtime image with resolved symbols, initialized memory, and executable
// instructions.
import peggy from 'peggy';
import fs from 'node:fs';
import { generate as astringGenerate } from 'astring';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
import SNOBOL from '../src/SNOBOL/base.js';

import '../src/SNOBOL/string.js';
import '../src/SNOBOL/mem.js';
import '../src/SNOBOL/syntax.js';
import '../src/SNOBOL/datatypes.js';
import '../src/SNOBOL/io.js';
import '../src/SNOBOL/file.js';
import '../src/SNOBOL/vm.js';
import '../src/SNOBOL/sil.js';
import '../src/SNOBOL/assemble.js';

function indent( text, spaces ) {
    const prefix = ' '.repeat( spaces );
    return text.split( '\n' ).map( line => prefix + line ).join( '\n' );
}

// One statement per line keeps the data and instruction sections shaped
// like a SIL listing: each line is a resolved declaration or instruction.
function serializeStatements( statements ) {
    return statements
        .map( stmt => '    ' + JSON.stringify( stmt ) )
        .join( ',\n' );
}

function serializeImage( image ) {
    return [
        'SNOBOL.image = {',
        '  "symbols": ' + indent( JSON.stringify( image.symbols, null, 2 ), 2 ).trimStart() + ',',
        '  "data": [',
        serializeStatements( image.data ),
        '  ],',
        '  "instructions": [',
        serializeStatements( image.instructions ),
        '  ]',
        '};',
        ''
    ].join( '\n' );
}

const __dirname = dirname( fileURLToPath( import.meta.url ) );
const source = __dirname + '/../external/v311-snoflake.sil',
      grammar = fs.readFileSync( __dirname + '/sil.peg' ).toString( 'utf-8' ),
      snobol = fs.readFileSync( source ).toString( 'utf-8' ),
      parser = peggy.generate( grammar ),
      ast = parser.parse( snobol ),
      prolog = [
          '// This file was automatically generated by translator/translate.js.',
          '// Source: external/v311-snoflake.sil',
          '// Image sections: resolved symbols, data declarations, and resolved instructions.',
          "import SNOBOL from './base.js';",
          ''
      ].join( '\n' ),
      sourceListing = astringGenerate( ast ).trim();

Function( 'SNOBOL', sourceListing )( SNOBOL );

const vm = new SNOBOL.VM(),
      image = SNOBOL.assemble( vm, SNOBOL.interp( vm ) ),
      code = prolog + serializeImage( image );

process.stdout.write( code );
